import type { Build, PromptDef, ResourceDef, ToolDef } from '@/lib/store/types'
import { slugify } from '@/lib/build/slug'
import type { FileEntry } from '../types'
import { pythonModuleName } from './util'

export function generateMain(build: Build): FileEntry {
  const moduleName = pythonModuleName(build.packageMeta.name)
  const lines = [
    'from .server import create_server',
    '',
    '',
    'def main() -> None:',
    '    server = create_server()',
    '    server.run()',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
  ]
  return {
    path: `src/${moduleName}/__main__.py`,
    content: lines.join('\n') + '\n',
  }
}

export function generateReadme(build: Build): FileEntry {
  const meta = build.packageMeta
  const name = slugify(meta.name || 'mcp-server')
  const tools = build.nodes
    .filter((n) => n.type === 'tool')
    .map((n) => (n.data as ToolDef).name)
  const prompts = build.nodes
    .filter((n) => n.type === 'prompt')
    .map((n) => (n.data as PromptDef).name)
  const resources = build.nodes
    .filter((n) => n.type === 'resource')
    .map((n) => (n.data as ResourceDef).uri)

  const lines: string[] = []
  lines.push(`# ${name}`)
  lines.push('')
  if (meta.description) {
    lines.push(meta.description)
    lines.push('')
  }
  lines.push('Generated by Argus.')
  lines.push('')
  lines.push('## Install')
  lines.push('')
  lines.push('```sh')
  lines.push('pip install -e .')
  lines.push('```')
  lines.push('')
  lines.push('## Run')
  lines.push('')
  lines.push('```sh')
  lines.push(name)
  lines.push('```')
  lines.push('')
  if (tools.length > 0) {
    lines.push('## Tools')
    lines.push('')
    for (const t of tools) lines.push(`- \`${t}\``)
    lines.push('')
  }
  if (prompts.length > 0) {
    lines.push('## Prompts')
    lines.push('')
    for (const p of prompts) lines.push(`- \`${p}\``)
    lines.push('')
  }
  if (resources.length > 0) {
    lines.push('## Resources')
    lines.push('')
    for (const r of resources) lines.push(`- \`${r}\``)
    lines.push('')
  }
  return { path: 'README.md', content: lines.join('\n') }
}

export function generateGitignore(): FileEntry {
  const content = [
    '__pycache__/',
    '*.pyc',
    '.venv/',
    'venv/',
    'dist/',
    'build/',
    '*.egg-info/',
    '.DS_Store',
    '',
  ].join('\n')
  return { path: '.gitignore', content }
}
